// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(CocaColaContext))]
    [Migration("20190524064146_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.CocaColaProduct", b =>
                {
                    b.Property<int>("MaterialCode")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Actual_Price_PerBottle");

                    b.Property<double>("Actual_Price_PerCase");

                    b.Property<int?>("Added_By");

                    b.Property<string>("Added_Date");

                    b.Property<string>("Brand_Name");

                    b.Property<string>("Description");

                    b.Property<string>("Image_Path");

                    b.Property<string>("Material_Package");

                    b.Property<int>("Material_Size");

                    b.Property<string>("Material_Type");

                    b.Property<string>("Material_Unit_Size");

                    b.Property<double>("RemainingQTY");

                    b.Property<double>("Suggested_Price_PerBottle");

                    b.Property<double>("Suggested_Price_PerCase");

                    b.Property<int?>("Updated_By");

                    b.Property<string>("Updated_Date");

                    b.Property<int>("Wholesaler_Id");

                    b.Property<bool>("isActive");

                    b.Property<bool>("isCokeProduct");

                    b.HasKey("MaterialCode");

                    b.ToTable("CocaColaProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
